### ISSUE TITLE
Python execution error

### ISSUE THREAD

**Issue by tripasect** [rikumi/iconsur#28]
Hey
Thanks for this beautiful project. I used it to change about 10 icons. After that, it suddenly broke. Seems like there's an issue with Python executions in background. Here's the error:

`Found iOS app: Spotify: Discover new music with icon: https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/0f/6e/0e/0f6e0ecd-e5b6-fe2a-ab1a-edb4d7a54cfd/source/512x512bb.jpg
If this app is incorrect, specify the correct name with -k or --keyword, or generate an icon locally with option -l or --local
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Cocoa/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 27, in <module>
    from objc._convenience import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 24, in <module>
    import collections
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 24, in <module>
    import heapq as _heapq
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/heapq.py", line 132, in <module>
    from itertools import islice, count, imap, izip, tee, chain
ImportError: cannot import name islice
fileicon-033326.sh: ERROR: ABORTING due to unexpected error.
Failed to set custom icon: fileicon script exited with error 1
`

**Comment by hsuehpascal** [comment]
I have a similar issue. After upgrading to 12.3 Beta (21E5196i) there has been a python execution error.

```
Processing /Applications/Google Docs.app...
Searching iOS App with name: Google Docs
Found iOS app: Google Docs: Sync, Edit, Share with icon: https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/dc/26/c6/dc26c631-c1e0-4e78-c49c-8c5460276688/source/512x512bb.jpg
If this app is incorrect, specify the correct name with -k or --keyword, or generate an icon locally with option -l or --local
/tmp/fileicon-244287.sh: line 203: /usr/bin/python: No such file or directory
fileicon-244287.sh: ERROR: ABORTING due to unexpected error.
Failed to set custom icon: fileicon script exited with error 1
```

Python is installed via homebrew and I've also tried reinstalling iconsur, and relinking and reinstalling python.
